version: '3.9'

services:
  broker:
    image: broker:1
    build:
      context: ./Broker
      dockerfile: Dockerfile
    ports:
      - "4545:4545"
    restart: always
  
  consumer:
    image: consumer:1
    build:
      context: ./Consumer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - broker
    restart: always

  web:
    image: web:1
    build:
      context: ./Web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - consumer

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Porta padrão para conexões AMQP
      - "15672:15672"  # Porta do painel de controle do RabbitMQ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Volume para persistir os dados
    restart: always

volumes:
  rabbitmq_data: